USE ExampleDatabase

DROP TABLE IF EXISTS ToDoList_App.TestSP CASCADE;

CREATE TABLE ToDoList_App.TestSP
( ID int generated by default as identity
, Payload varchar(255)
);

ALTER TABLE ToDoList_App.TestSP ALTER ID SET NOT NULL;
ALTER TABLE ToDoList_App.TestSP ALTER Payload SET NOT NULL;

ALTER TABLE ToDoList_App.TestSP
 ADD CONSTRAINT TESTSP_PKEY PRIMARY KEY
  ( ID
  )
;

