USE ExampleDatabase

DROP TABLE IF EXISTS ToDoList_App.TestEnum CASCADE;

CREATE TABLE ToDoList_App.TestEnum
( ID int generated by default as identity
, NodeTypeCharEn character(1) -- beware char to varchar morph
, IntEn integer
);

ALTER TABLE ToDoList_App.TestEnum ALTER ID SET NOT NULL;
ALTER TABLE ToDoList_App.TestEnum ALTER NodeTypeCharEn SET NOT NULL;
ALTER TABLE ToDoList_App.TestEnum ALTER IntEn SET NOT NULL;

ALTER TABLE ToDoList_App.TestEnum
 ADD CONSTRAINT TESTENUM_PKEY PRIMARY KEY
  ( ID
  )
;

