USE ExampleDatabase

DROP TABLE IF EXISTS ToDoList_App.TestJSON CASCADE;

CREATE TABLE ToDoList_App.TestJSON
( ID int generated by default as identity
, Payload jsonb
);

ALTER TABLE ToDoList_App.TestJSON ALTER ID SET NOT NULL;
ALTER TABLE ToDoList_App.TestJSON ALTER Payload SET NOT NULL;

ALTER TABLE ToDoList_App.TestJSON
 ADD CONSTRAINT TESTJSON_PKEY PRIMARY KEY
  ( ID
  )
;

